
name: Brakeman Scan

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
permissions:
  contents: read

jobs:
  brakeman-scan: 
    permissions:
      contents: read 
      security-events: write 
      actions: read 
    name: Brakeman Scan
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: ruby/setup-ruby@v1
    - name: Set up Ruby
      uses: ruby/setup-ruby@55283cc23133118229fd3f97f9336ee23a179fcf # v1.146.0
      with:
        ruby-version: '2.7'

    - name: Setup Brakeman
      env:
        BRAKEMAN_VERSION: '4.10' 
      run: |
        gem install brakeman --version $BRAKEMAN_VERSION
    - name: Scan
      continue-on-error: true
      run: 
        brakeman -f sarif -o output.sarif.json .
    - name: Upload SARIF report
      uses: actions/upload-artifact@v2
      with:
       name: sarif-report
       path: output.sarif.json
       runs-on: ubuntu-latest
           
 
      
